### ISSUE TITLE
Missing configuration files

### ISSUE THREAD

**Issue by HIT-Ygq** [jiaying001/SE2LIO#1]
Hello! It seems that two important files, CMakeLists.txt and package.xml, are missing.

**Comment by jiaying001** [comment]
Hello! I uploaded just now.

**Comment by HIT-Ygq** [comment]
thanks! In addition to this, the rviz file is missing. But after I ran it, there was an error. How should I configure gnss_localizer? Or is it some other error?

![err](https://user-images.githubusercontent.com/90457565/234163303-385383de-c482-4ad3-812e-a82936e5792d.png)
![err2](https://user-images.githubusercontent.com/90457565/234163603-3acb18d5-60b1-4a56-969e-b4cfecfc1116.png)

**Comment by jiaying001** [comment]
The gnsss is another package that I use to convert GPS data. gnss package is not in this folder so it can't be founded.  You can delet that line.

Best Wishes
________________________________
发件人: Guoqiang Yin ***@***.***>
发送时间: 2023年4月25日 11:02
收件人: jiaying001/SE2LIO ***@***.***>
抄送: #CHEN JIAYING# ***@***.***>; State change ***@***.***>
主题: Re: [jiaying001/SE2LIO] Missing configuration files (Issue #1)


thanks! But after I ran it, there was an error. How should I configure gnss_localizer? Or is it some other error?

[err]<https://user-images.githubusercontent.com/90457565/234163303-385383de-c482-4ad3-812e-a82936e5792d.png>
[err2]<https://user-images.githubusercontent.com/90457565/234163603-3acb18d5-60b1-4a56-969e-b4cfecfc1116.png>

―
